// <auto-generated />
using System;
using AutoParkingSystem.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoParkingSystem.Repository.Migrations
{
    [DbContext(typeof(ParkDbContext))]
    [Migration("20240111124401_v0.0.1")]
    partial class v001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoParkingSystem.Model.ParkPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("license_plate_number");

                    b.Property<DateTime>("ParkInTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("park_in_time");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("position_name");

                    b.HasKey("Id");

                    b.ToTable("park_position");
                });
#pragma warning restore 612, 618
        }
    }
}
